// <auto-generated />
using ContactHopper.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactHopper.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181009193606_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactHopper.API.Data.Entities.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PhoneBookId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PhoneBookId");

                    b.ToTable("Entries");

                    b.HasData(
                        new { Id = 1, Name = "Mom", PhoneBookId = 1, PhoneNumber = "0533452690" },
                        new { Id = 2, Name = "Dad", PhoneBookId = 1, PhoneNumber = "0533452691" },
                        new { Id = 3, Name = "Wife", PhoneBookId = 1, PhoneNumber = "0533452692" },
                        new { Id = 4, Name = "Son", PhoneBookId = 1, PhoneNumber = "0533452693" },
                        new { Id = 5, Name = "Cousin", PhoneBookId = 1, PhoneNumber = "0533452694" },
                        new { Id = 6, Name = "Lead", PhoneBookId = 2, PhoneNumber = "0533452695" },
                        new { Id = 7, Name = "Friend", PhoneBookId = 2, PhoneNumber = "0533452696" },
                        new { Id = 8, Name = "New Guy", PhoneBookId = 2, PhoneNumber = "0533452697" }
                    );
                });

            modelBuilder.Entity("ContactHopper.API.Data.Entities.PhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("PhoneBooks");

                    b.HasData(
                        new { Id = 1, Name = "Family" },
                        new { Id = 2, Name = "Work" }
                    );
                });

            modelBuilder.Entity("ContactHopper.API.Data.Entities.Entry", b =>
                {
                    b.HasOne("ContactHopper.API.Data.Entities.PhoneBook", "PhoneBook")
                        .WithMany("Entries")
                        .HasForeignKey("PhoneBookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
